export const config = {
  MINIO_ENDPOINT: 'minio1',
  MINIO_PORT: 9000,
  MINIO_ACCESSKEY: 'SDGCXVFSGSDFSDZC',
  MINIO_SECRETKEY: 'ADGFDSGVCXFADZ/SDGCZVRSZCV/SDCXBsfvdvzsvsdzA',
  MINIO_BUCKET: 'photos',
}
