version: "3.8"
services:
  db:
    image: postgres:13.1-alpine
    restart: unless-stopped
    volumes:
      - ../db/:/var/lib/postgresql/data
    env_file:
      - docker.env
    networks:
      - ginyatovsite
    ports:
      - "5432:5432"
  #frontend:
  #  restart: unless-stopped
  #  networks:
  #    - ginyatovsite
  #  build:
  #    context: ../client
  #    dockerfile: Dockerfile.dev
  #  command: "yarn dev"
  #  expose:
  #    - "3000"
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.frontend.entrypoints=web"
  #    - "traefik.http.routers.frontend.rule=Host(`localhost`)"
  #  volumes:
  #    - ../client/src:/app/src
  #    - ../client/src/.next:/app/.next
  #    - ../client/public/uploads:/app/public/uploads
  #  depends_on:
  #    - strapi
  #api:
  #  restart: unless-stopped
  #  networks:
  #    - ginyatovsite
  #  build:
  #    context: ../server
  #    dockerfile: Dockerfile.dev
  #  command: "yarn start:dev"
  #  volumes:
  #    - ../server/src:/app/src
  #  ports:
  #    - 4000:4000
  #  depends_on:
  #    - db
  #  env_file:
  #    - ../server/.env
  #webserver:
  #  build:
  #    context: ../nginx
  #    dockerfile: Dockerfile.dev
  #  restart: unless-stopped
  #  working_dir: /var/www
  #  depends_on:
  #    - strapi
  #    - frontend
  #  ports:
  #    - "80:80"
  #  networks:
  #    - ginyatovsite



volumes:
  #minio-data:
  #admin:
  #server:
  traefik:
  strapi:
  db:
  frontend:


#Docker Networks
networks:
  ginyatovsite:
    external: true
    name: ginyatovsite
    driver: bridge
